
name: print-pdf


on: 
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Asian fonts
      run: |
        apt-get update
        apt-get -yq install xfonts-utils fonts-droid xfonts-intl-asian
        fc-cache -fv
    - run: npm install
    - run: npx hackmyresume build resume.json out/resume.all --theme positive
    - run: npx hackmyresume build resume-ja.json out-ja/resume.all --theme positive
    - run: node pdf-print.js
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "out/resume.pdf, out-ja/resume-ja.pdf"
